redis:
    build: ./redis
    ports:
      - "6379:6379"

mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ~/data/mysql:/var/lib/mysql

sentry:
    build: ./sentry
    ports:
      - "9001:9001"
    links:
      - mysql
      - redis