nginx:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - "php"
    volumes:
      - ~/data:/data

php:
    build: ./php
    ports:
      - "9000:9000"
    links:
      - "mysql"
      - "memcache"
      - "redis"
    volumes:
      - ~/data:/data

mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ~/data/mysql:/var/lib/mysql

memcache:
    build: ./memcache
    ports:
      - "11211:11211"

redis:
    build: ./redis
    ports:
      - "6379:6379"
    volumes:
      - ~/data:/data

node:
    build: ./node
    tty: true
    stdin_open: true
    volumes:
      - ~/data:/data
    extra_hosts:
      - "dev.m.com:192.168.59.103"