FROM node:0.12

RUN npm install -g cnpm

RUN cnpm install -g gulp

RUN cnpm install -g bower

RUN cnpm install -g phantomjs

RUN cnpm install -g casperjs

RUN cnpm install -g mocha-casperjs

RUN cnpm install -g casper-chai

RUN cnpm install -g chai

RUN cnpm install -g mocha

RUN npm cache clear

WORKDIR /data

VOLUME ["/data"]
